/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowAG (void)
{
  GtkWidget *windowAG;
  GtkWidget *fixed1;
  GtkWidget *entryAGFrechercher;
  GtkWidget *backAGF;
  GtkWidget *radiobuttonAGFrechercher_Cin;
  GSList *radiobuttonAGFrechercher_Cin_group = NULL;
  GtkWidget *radiobuttonAGFrechercher_Chambre;
  GtkWidget *radiobuttonAGFrechercher_nom;
  GtkWidget *notebook2;
  GtkWidget *scrolledwindowAGF;
  GtkWidget *treeviewAGF;
  GtkWidget *labeltabAGF1;
  GtkWidget *fixed2;
  GtkWidget *entryAGFnom;
  GtkWidget *labelAGFprenom;
  GtkWidget *entryAGFprenom;
  GtkWidget *entryAGFchambre;
  GtkWidget *entryAGFcin;
  GtkWidget *entryAGFtelf;
  GtkObject *spinbuttonAGFj_adj;
  GtkWidget *spinbuttonAGFj;
  GtkObject *spinbuttonAGFm_adj;
  GtkWidget *spinbuttonAGFm;
  GtkObject *spinbuttonAGFa_adj;
  GtkWidget *spinbuttonAGFa;
  GtkWidget *labelAGFnom;
  GtkWidget *labelAGFinva_cin;
  GtkWidget *labelAGFinva_telf;
  GtkWidget *labelAGFdate;
  GtkWidget *labelAGFj;
  GtkWidget *labelAGFm;
  GtkWidget *labelAGFa;
  GtkWidget *comboboxAGFniv;
  GtkWidget *labelAGF;
  GtkWidget *comboboxAGFspc;
  GtkWidget *labelAGFchambre;
  GtkWidget *labelAGFcin;
  GtkWidget *labelAGFtelf;
  GtkWidget *labelAGFinva_nom;
  GtkWidget *labelAGFinva_prenom;
  GtkWidget *labelAGFinva_chambre;
  GtkWidget *buttonAGFajouter;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image6;
  GtkWidget *label3;
  GtkWidget *labeltabAGF2;
  GtkWidget *fixed3;
  GtkWidget *entryAGFmodifnom;
  GtkWidget *entryAGFmodifprenom;
  GtkWidget *entryAGFmodifchambre;
  GtkWidget *entryAGFmodiftelf;
  GtkWidget *labelmodfnom;
  GtkWidget *labelmodfniveau;
  GtkWidget *radiobuttonAGFm1;
  GSList *radiobuttonAGFm1_group = NULL;
  GtkWidget *radiobuttonAGFm2;
  GtkWidget *labelModfprenom;
  GtkWidget *radiobuttonAGFm3;
  GtkWidget *radiobuttonAGFm4;
  GtkWidget *radiobuttonAGFm5;
  GtkWidget *labelmodfchambre;
  GtkWidget *labelmodftelf;
  GtkWidget *buttonAGFinfo;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image4;
  GtkWidget *label1;
  GtkWidget *buttonAGFmodif;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image5;
  GtkWidget *label2;
  GtkWidget *labeltabAGF3;
  GtkWidget *buttonAGFrechercher;
  GtkWidget *image2;
  GtkWidget *buttonAGFsupprimer;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image7;
  GtkWidget *label4;
  GtkWidget *buttonwindocalculer;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image8;
  GtkWidget *label5;
  GtkWidget *image12;
  GtkWidget *labelAGfespace;
  GtkWidget *imagelogo;
  GtkWidget *button_afficherAGF;
  GtkWidget *image3;
  GtkWidget *calendar1;
  GtkWidget *labelAGFtime;

  windowAG = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowAG, 1200, 700);
  gtk_window_set_title (GTK_WINDOW (windowAG), _("Agent du foyer"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (windowAG), fixed1);

  entryAGFrechercher = gtk_entry_new ();
  gtk_widget_show (entryAGFrechercher);
  gtk_fixed_put (GTK_FIXED (fixed1), entryAGFrechercher, 584, 96);
  gtk_widget_set_size_request (entryAGFrechercher, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryAGFrechercher), 8226);

  backAGF = create_pixmap (windowAG, "perf.jpg");
  gtk_widget_show (backAGF);
  gtk_fixed_put (GTK_FIXED (fixed1), backAGF, 0, 0);
  gtk_widget_set_size_request (backAGF, 1200, 700);

  radiobuttonAGFrechercher_Cin = gtk_radio_button_new_with_mnemonic (NULL, _("Cin"));
  gtk_widget_show (radiobuttonAGFrechercher_Cin);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobuttonAGFrechercher_Cin, 528, 96);
  gtk_widget_set_size_request (radiobuttonAGFrechercher_Cin, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonAGFrechercher_Cin), radiobuttonAGFrechercher_Cin_group);
  radiobuttonAGFrechercher_Cin_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonAGFrechercher_Cin));

  radiobuttonAGFrechercher_Chambre = gtk_radio_button_new_with_mnemonic (NULL, _("Chambre"));
  gtk_widget_show (radiobuttonAGFrechercher_Chambre);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobuttonAGFrechercher_Chambre, 432, 96);
  gtk_widget_set_size_request (radiobuttonAGFrechercher_Chambre, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonAGFrechercher_Chambre), radiobuttonAGFrechercher_Cin_group);
  radiobuttonAGFrechercher_Cin_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonAGFrechercher_Chambre));

  radiobuttonAGFrechercher_nom = gtk_radio_button_new_with_mnemonic (NULL, _("Nom"));
  gtk_widget_show (radiobuttonAGFrechercher_nom);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobuttonAGFrechercher_nom, 352, 96);
  gtk_widget_set_size_request (radiobuttonAGFrechercher_nom, 107, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonAGFrechercher_nom), radiobuttonAGFrechercher_Cin_group);
  radiobuttonAGFrechercher_Cin_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonAGFrechercher_nom));

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook2, 368, 128);
  gtk_widget_set_size_request (notebook2, 688, 520);

  scrolledwindowAGF = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindowAGF);
  gtk_container_add (GTK_CONTAINER (notebook2), scrolledwindowAGF);

  treeviewAGF = gtk_tree_view_new ();
  gtk_widget_show (treeviewAGF);
  gtk_container_add (GTK_CONTAINER (scrolledwindowAGF), treeviewAGF);

  labeltabAGF1 = gtk_label_new (_("Menu"));
  gtk_widget_show (labeltabAGF1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), labeltabAGF1);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed2);

  entryAGFnom = gtk_entry_new ();
  gtk_widget_show (entryAGFnom);
  gtk_fixed_put (GTK_FIXED (fixed2), entryAGFnom, 88, 16);
  gtk_widget_set_size_request (entryAGFnom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryAGFnom), 8226);

  labelAGFprenom = gtk_label_new (_("Prenom :"));
  gtk_widget_show (labelAGFprenom);
  gtk_fixed_put (GTK_FIXED (fixed2), labelAGFprenom, 8, 64);
  gtk_widget_set_size_request (labelAGFprenom, 72, 16);

  entryAGFprenom = gtk_entry_new ();
  gtk_widget_show (entryAGFprenom);
  gtk_fixed_put (GTK_FIXED (fixed2), entryAGFprenom, 96, 64);
  gtk_widget_set_size_request (entryAGFprenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryAGFprenom), 8226);

  entryAGFchambre = gtk_entry_new ();
  gtk_widget_show (entryAGFchambre);
  gtk_fixed_put (GTK_FIXED (fixed2), entryAGFchambre, 128, 264);
  gtk_widget_set_size_request (entryAGFchambre, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryAGFchambre), 8226);

  entryAGFcin = gtk_entry_new ();
  gtk_widget_show (entryAGFcin);
  gtk_fixed_put (GTK_FIXED (fixed2), entryAGFcin, 128, 336);
  gtk_widget_set_size_request (entryAGFcin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryAGFcin), 8226);

  entryAGFtelf = gtk_entry_new ();
  gtk_widget_show (entryAGFtelf);
  gtk_fixed_put (GTK_FIXED (fixed2), entryAGFtelf, 152, 392);
  gtk_widget_set_size_request (entryAGFtelf, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryAGFtelf), 8226);

  spinbuttonAGFj_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonAGFj = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonAGFj_adj), 1, 0);
  gtk_widget_show (spinbuttonAGFj);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonAGFj, 200, 104);
  gtk_widget_set_size_request (spinbuttonAGFj, 60, 27);

  spinbuttonAGFm_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonAGFm = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonAGFm_adj), 1, 0);
  gtk_widget_show (spinbuttonAGFm);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonAGFm, 320, 112);
  gtk_widget_set_size_request (spinbuttonAGFm, 60, 27);

  spinbuttonAGFa_adj = gtk_adjustment_new (1990, 1970, 2006, 1, 10, 10);
  spinbuttonAGFa = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonAGFa_adj), 1, 0);
  gtk_widget_show (spinbuttonAGFa);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonAGFa, 464, 112);
  gtk_widget_set_size_request (spinbuttonAGFa, 60, 27);

  labelAGFnom = gtk_label_new (_("Nom :"));
  gtk_widget_show (labelAGFnom);
  gtk_fixed_put (GTK_FIXED (fixed2), labelAGFnom, 8, 24);
  gtk_widget_set_size_request (labelAGFnom, 64, 17);

  labelAGFinva_cin = gtk_label_new ("");
  gtk_widget_show (labelAGFinva_cin);
  gtk_fixed_put (GTK_FIXED (fixed2), labelAGFinva_cin, 296, 328);
  gtk_widget_set_size_request (labelAGFinva_cin, 232, 40);

  labelAGFinva_telf = gtk_label_new ("");
  gtk_widget_show (labelAGFinva_telf);
  gtk_fixed_put (GTK_FIXED (fixed2), labelAGFinva_telf, 320, 392);
  gtk_widget_set_size_request (labelAGFinva_telf, 248, 41);

  labelAGFdate = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (labelAGFdate);
  gtk_fixed_put (GTK_FIXED (fixed2), labelAGFdate, 0, 112);
  gtk_widget_set_size_request (labelAGFdate, 160, 16);

  labelAGFj = gtk_label_new (_("jour"));
  gtk_widget_show (labelAGFj);
  gtk_fixed_put (GTK_FIXED (fixed2), labelAGFj, 152, 112);
  gtk_widget_set_size_request (labelAGFj, 49, 17);

  labelAGFm = gtk_label_new (_("Mois"));
  gtk_widget_show (labelAGFm);
  gtk_fixed_put (GTK_FIXED (fixed2), labelAGFm, 272, 112);
  gtk_widget_set_size_request (labelAGFm, 49, 17);

  labelAGFa = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (labelAGFa);
  gtk_fixed_put (GTK_FIXED (fixed2), labelAGFa, 408, 112);
  gtk_widget_set_size_request (labelAGFa, 49, 17);

  comboboxAGFniv = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxAGFniv);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxAGFniv, 104, 184);
  gtk_widget_set_size_request (comboboxAGFniv, 64, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAGFniv), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAGFniv), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAGFniv), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAGFniv), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAGFniv), _("5"));

  labelAGF = gtk_label_new (_("Niveau :"));
  gtk_widget_show (labelAGF);
  gtk_fixed_put (GTK_FIXED (fixed2), labelAGF, 16, 192);
  gtk_widget_set_size_request (labelAGF, 80, 16);

  comboboxAGFspc = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxAGFspc);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxAGFspc, 200, 184);
  gtk_widget_set_size_request (comboboxAGFspc, 120, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAGFspc), _("A"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAGFspc), _("B"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAGFspc), _("GC"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAGFspc), _("IA"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAGFspc), _("ARCTIC"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAGFspc), _("ERP-BI"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAGFspc), _("DS"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAGFspc), _("INFINI"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAGFspc), _("IoSyS"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAGFspc), _("M\303\251caT"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAGFspc), _("NIDS"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAGFspc), _("OGI"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAGFspc), _("SAE"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAGFspc), _("SE"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAGFspc), _("SIM"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAGFspc), _("SLEAM"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxAGFspc), _("TWIN"));

  labelAGFchambre = gtk_label_new (_("N\302\260 Chambre"));
  gtk_widget_show (labelAGFchambre);
  gtk_fixed_put (GTK_FIXED (fixed2), labelAGFchambre, 16, 272);
  gtk_widget_set_size_request (labelAGFchambre, 112, 17);

  labelAGFcin = gtk_label_new (_("Cin :"));
  gtk_widget_show (labelAGFcin);
  gtk_fixed_put (GTK_FIXED (fixed2), labelAGFcin, 32, 328);
  gtk_widget_set_size_request (labelAGFcin, 41, 17);

  labelAGFtelf = gtk_label_new (_("Num de t\303\251l\303\251phone :"));
  gtk_widget_show (labelAGFtelf);
  gtk_fixed_put (GTK_FIXED (fixed2), labelAGFtelf, 0, 400);
  gtk_widget_set_size_request (labelAGFtelf, 152, 16);

  labelAGFinva_nom = gtk_label_new ("");
  gtk_widget_show (labelAGFinva_nom);
  gtk_fixed_put (GTK_FIXED (fixed2), labelAGFinva_nom, 264, 8);
  gtk_widget_set_size_request (labelAGFinva_nom, 232, 33);

  labelAGFinva_prenom = gtk_label_new ("");
  gtk_widget_show (labelAGFinva_prenom);
  gtk_fixed_put (GTK_FIXED (fixed2), labelAGFinva_prenom, 264, 64);
  gtk_widget_set_size_request (labelAGFinva_prenom, 240, 32);

  labelAGFinva_chambre = gtk_label_new ("");
  gtk_widget_show (labelAGFinva_chambre);
  gtk_fixed_put (GTK_FIXED (fixed2), labelAGFinva_chambre, 296, 264);
  gtk_widget_set_size_request (labelAGFinva_chambre, 232, 33);

  buttonAGFajouter = gtk_button_new ();
  gtk_widget_show (buttonAGFajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonAGFajouter, 568, 448);
  gtk_widget_set_size_request (buttonAGFajouter, 96, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonAGFajouter), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image6 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox3), image6, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  labeltabAGF2 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (labeltabAGF2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), labeltabAGF2);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed3);

  entryAGFmodifnom = gtk_entry_new ();
  gtk_widget_show (entryAGFmodifnom);
  gtk_fixed_put (GTK_FIXED (fixed3), entryAGFmodifnom, 128, 64);
  gtk_widget_set_size_request (entryAGFmodifnom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryAGFmodifnom), 8226);

  entryAGFmodifprenom = gtk_entry_new ();
  gtk_widget_show (entryAGFmodifprenom);
  gtk_fixed_put (GTK_FIXED (fixed3), entryAGFmodifprenom, 120, 144);
  gtk_widget_set_size_request (entryAGFmodifprenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryAGFmodifprenom), 8226);

  entryAGFmodifchambre = gtk_entry_new ();
  gtk_widget_show (entryAGFmodifchambre);
  gtk_fixed_put (GTK_FIXED (fixed3), entryAGFmodifchambre, 136, 296);
  gtk_widget_set_size_request (entryAGFmodifchambre, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryAGFmodifchambre), 8226);

  entryAGFmodiftelf = gtk_entry_new ();
  gtk_widget_show (entryAGFmodiftelf);
  gtk_fixed_put (GTK_FIXED (fixed3), entryAGFmodiftelf, 152, 368);
  gtk_widget_set_size_request (entryAGFmodiftelf, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryAGFmodiftelf), 8226);

  labelmodfnom = gtk_label_new (_("Nom :"));
  gtk_widget_show (labelmodfnom);
  gtk_fixed_put (GTK_FIXED (fixed3), labelmodfnom, 32, 72);
  gtk_widget_set_size_request (labelmodfnom, 56, 16);

  labelmodfniveau = gtk_label_new (_("Niveau :"));
  gtk_widget_show (labelmodfniveau);
  gtk_fixed_put (GTK_FIXED (fixed3), labelmodfniveau, 24, 224);
  gtk_widget_set_size_request (labelmodfniveau, 72, 17);

  radiobuttonAGFm1 = gtk_radio_button_new_with_mnemonic (NULL, _("1"));
  gtk_widget_show (radiobuttonAGFm1);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobuttonAGFm1, 104, 224);
  gtk_widget_set_size_request (radiobuttonAGFm1, 48, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonAGFm1), radiobuttonAGFm1_group);
  radiobuttonAGFm1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonAGFm1));

  radiobuttonAGFm2 = gtk_radio_button_new_with_mnemonic (NULL, _("2"));
  gtk_widget_show (radiobuttonAGFm2);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobuttonAGFm2, 160, 224);
  gtk_widget_set_size_request (radiobuttonAGFm2, 48, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonAGFm2), radiobuttonAGFm1_group);
  radiobuttonAGFm1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonAGFm2));

  labelModfprenom = gtk_label_new (_("Prenom :"));
  gtk_widget_show (labelModfprenom);
  gtk_fixed_put (GTK_FIXED (fixed3), labelModfprenom, 24, 152);
  gtk_widget_set_size_request (labelModfprenom, 64, 17);

  radiobuttonAGFm3 = gtk_radio_button_new_with_mnemonic (NULL, _("3"));
  gtk_widget_show (radiobuttonAGFm3);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobuttonAGFm3, 224, 224);
  gtk_widget_set_size_request (radiobuttonAGFm3, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonAGFm3), radiobuttonAGFm1_group);
  radiobuttonAGFm1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonAGFm3));

  radiobuttonAGFm4 = gtk_radio_button_new_with_mnemonic (NULL, _("4"));
  gtk_widget_show (radiobuttonAGFm4);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobuttonAGFm4, 104, 256);
  gtk_widget_set_size_request (radiobuttonAGFm4, 48, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonAGFm4), radiobuttonAGFm1_group);
  radiobuttonAGFm1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonAGFm4));

  radiobuttonAGFm5 = gtk_radio_button_new_with_mnemonic (NULL, _("5"));
  gtk_widget_show (radiobuttonAGFm5);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobuttonAGFm5, 152, 256);
  gtk_widget_set_size_request (radiobuttonAGFm5, 56, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonAGFm5), radiobuttonAGFm1_group);
  radiobuttonAGFm1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonAGFm5));

  labelmodfchambre = gtk_label_new (_("Chambre :"));
  gtk_widget_show (labelmodfchambre);
  gtk_fixed_put (GTK_FIXED (fixed3), labelmodfchambre, 24, 304);
  gtk_widget_set_size_request (labelmodfchambre, 80, 24);

  labelmodftelf = gtk_label_new (_("Num de t\303\251l\303\251phone :"));
  gtk_widget_show (labelmodftelf);
  gtk_fixed_put (GTK_FIXED (fixed3), labelmodftelf, 0, 368);
  gtk_widget_set_size_request (labelmodftelf, 144, 25);

  buttonAGFinfo = gtk_button_new ();
  gtk_widget_show (buttonAGFinfo);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonAGFinfo, 600, 16);
  gtk_widget_set_size_request (buttonAGFinfo, 66, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonAGFinfo), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image4 = gtk_image_new_from_stock ("gtk-help", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox1), image4, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Info"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  buttonAGFmodif = gtk_button_new ();
  gtk_widget_show (buttonAGFmodif);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonAGFmodif, 504, 384);
  gtk_widget_set_size_request (buttonAGFmodif, 112, 37);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonAGFmodif), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image5 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox2), image5, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  labeltabAGF3 = gtk_label_new (_("Modifier"));
  gtk_widget_show (labeltabAGF3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), labeltabAGF3);

  buttonAGFrechercher = gtk_button_new ();
  gtk_widget_show (buttonAGFrechercher);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonAGFrechercher, 752, 88);
  gtk_widget_set_size_request (buttonAGFrechercher, 40, 40);
  gtk_container_set_border_width (GTK_CONTAINER (buttonAGFrechercher), 1);
  gtk_button_set_relief (GTK_BUTTON (buttonAGFrechercher), GTK_RELIEF_HALF);

  image2 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_DND);
  gtk_widget_show (image2);
  gtk_container_add (GTK_CONTAINER (buttonAGFrechercher), image2);

  buttonAGFsupprimer = gtk_button_new ();
  gtk_widget_show (buttonAGFsupprimer);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonAGFsupprimer, 936, 656);
  gtk_widget_set_size_request (buttonAGFsupprimer, 120, 35);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonAGFsupprimer), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image7 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox4), image7, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  buttonwindocalculer = gtk_button_new ();
  gtk_widget_show (buttonwindocalculer);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonwindocalculer, 376, 656);
  gtk_widget_set_size_request (buttonwindocalculer, 120, 35);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttonwindocalculer), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image8 = gtk_image_new_from_stock ("gtk-convert", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox5), image8, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Calculer"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox5), label5, FALSE, FALSE, 0);

  image12 = create_pixmap (windowAG, "perf.jpg");
  gtk_widget_show (image12);
  gtk_fixed_put (GTK_FIXED (fixed1), image12, 616, 800);
  gtk_widget_set_size_request (image12, 41, 17);

  labelAGfespace = gtk_label_new (_("<span foreground=\"red\"><b>AGENT DE FOYER</b></span>"));
  gtk_widget_show (labelAGfespace);
  gtk_fixed_put (GTK_FIXED (fixed1), labelAGfespace, 632, 24);
  gtk_widget_set_size_request (labelAGfespace, 208, 33);
  gtk_label_set_use_markup (GTK_LABEL (labelAGfespace), TRUE);

  imagelogo = create_pixmap (windowAG, "Logo_ESPRIT_-_Tunisie-ConvertImage.png");
  gtk_widget_show (imagelogo);
  gtk_fixed_put (GTK_FIXED (fixed1), imagelogo, 8, 8);
  gtk_widget_set_size_request (imagelogo, 192, 72);

  button_afficherAGF = gtk_button_new ();
  gtk_widget_show (button_afficherAGF);
  gtk_fixed_put (GTK_FIXED (fixed1), button_afficherAGF, 1000, 96);
  gtk_widget_set_size_request (button_afficherAGF, 40, 37);

  image3 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_DND);
  gtk_widget_show (image3);
  gtk_container_add (GTK_CONTAINER (button_afficherAGF), image3);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed1), calendar1, 96, 392);
  gtk_widget_set_size_request (calendar1, 162, 186);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  labelAGFtime = gtk_label_new ("");
  gtk_widget_show (labelAGFtime);
  gtk_fixed_put (GTK_FIXED (fixed1), labelAGFtime, 56, 320);
  gtk_widget_set_size_request (labelAGFtime, 232, 48);

  g_signal_connect ((gpointer) radiobuttonAGFrechercher_Cin, "toggled",
                    G_CALLBACK (on_radiobuttonAGFrechercher_Cin_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonAGFrechercher_Chambre, "toggled",
                    G_CALLBACK (on_radiobuttonAGFrechercher_Chambre_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonAGFrechercher_nom, "toggled",
                    G_CALLBACK (on_radiobuttonAGFrechercher_nom_toggled),
                    NULL);
  g_signal_connect ((gpointer) treeviewAGF, "row_activated",
                    G_CALLBACK (on_treeviewAGF_row_activated),
                    NULL);
  g_signal_connect ((gpointer) buttonAGFajouter, "clicked",
                    G_CALLBACK (on_buttonAGFajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonAGFm1, "toggled",
                    G_CALLBACK (on_radiobuttonAGFm1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonAGFm2, "toggled",
                    G_CALLBACK (on_radiobuttonAGFm2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonAGFm3, "toggled",
                    G_CALLBACK (on_radiobuttonAGFm3_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonAGFm4, "toggled",
                    G_CALLBACK (on_radiobuttonAGFm4_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonAGFm5, "toggled",
                    G_CALLBACK (on_radiobuttonAGFm5_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonAGFinfo, "clicked",
                    G_CALLBACK (on_buttonAGFinfo_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAGFmodif, "clicked",
                    G_CALLBACK (on_buttonAGFmodif_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAGFrechercher, "clicked",
                    G_CALLBACK (on_buttonAGFrechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAGFsupprimer, "clicked",
                    G_CALLBACK (on_buttonAGFsupprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonwindocalculer, "clicked",
                    G_CALLBACK (on_buttonwindocalculer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_afficherAGF, "clicked",
                    G_CALLBACK (on_button_afficherAGF_clicked),
                    NULL);
  g_signal_connect ((gpointer) calendar1, "day_selected_double_click",
                    G_CALLBACK (on_calendar1_day_selected_double_click),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowAG, windowAG, "windowAG");
  GLADE_HOOKUP_OBJECT (windowAG, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (windowAG, entryAGFrechercher, "entryAGFrechercher");
  GLADE_HOOKUP_OBJECT (windowAG, backAGF, "backAGF");
  GLADE_HOOKUP_OBJECT (windowAG, radiobuttonAGFrechercher_Cin, "radiobuttonAGFrechercher_Cin");
  GLADE_HOOKUP_OBJECT (windowAG, radiobuttonAGFrechercher_Chambre, "radiobuttonAGFrechercher_Chambre");
  GLADE_HOOKUP_OBJECT (windowAG, radiobuttonAGFrechercher_nom, "radiobuttonAGFrechercher_nom");
  GLADE_HOOKUP_OBJECT (windowAG, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (windowAG, scrolledwindowAGF, "scrolledwindowAGF");
  GLADE_HOOKUP_OBJECT (windowAG, treeviewAGF, "treeviewAGF");
  GLADE_HOOKUP_OBJECT (windowAG, labeltabAGF1, "labeltabAGF1");
  GLADE_HOOKUP_OBJECT (windowAG, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (windowAG, entryAGFnom, "entryAGFnom");
  GLADE_HOOKUP_OBJECT (windowAG, labelAGFprenom, "labelAGFprenom");
  GLADE_HOOKUP_OBJECT (windowAG, entryAGFprenom, "entryAGFprenom");
  GLADE_HOOKUP_OBJECT (windowAG, entryAGFchambre, "entryAGFchambre");
  GLADE_HOOKUP_OBJECT (windowAG, entryAGFcin, "entryAGFcin");
  GLADE_HOOKUP_OBJECT (windowAG, entryAGFtelf, "entryAGFtelf");
  GLADE_HOOKUP_OBJECT (windowAG, spinbuttonAGFj, "spinbuttonAGFj");
  GLADE_HOOKUP_OBJECT (windowAG, spinbuttonAGFm, "spinbuttonAGFm");
  GLADE_HOOKUP_OBJECT (windowAG, spinbuttonAGFa, "spinbuttonAGFa");
  GLADE_HOOKUP_OBJECT (windowAG, labelAGFnom, "labelAGFnom");
  GLADE_HOOKUP_OBJECT (windowAG, labelAGFinva_cin, "labelAGFinva_cin");
  GLADE_HOOKUP_OBJECT (windowAG, labelAGFinva_telf, "labelAGFinva_telf");
  GLADE_HOOKUP_OBJECT (windowAG, labelAGFdate, "labelAGFdate");
  GLADE_HOOKUP_OBJECT (windowAG, labelAGFj, "labelAGFj");
  GLADE_HOOKUP_OBJECT (windowAG, labelAGFm, "labelAGFm");
  GLADE_HOOKUP_OBJECT (windowAG, labelAGFa, "labelAGFa");
  GLADE_HOOKUP_OBJECT (windowAG, comboboxAGFniv, "comboboxAGFniv");
  GLADE_HOOKUP_OBJECT (windowAG, labelAGF, "labelAGF");
  GLADE_HOOKUP_OBJECT (windowAG, comboboxAGFspc, "comboboxAGFspc");
  GLADE_HOOKUP_OBJECT (windowAG, labelAGFchambre, "labelAGFchambre");
  GLADE_HOOKUP_OBJECT (windowAG, labelAGFcin, "labelAGFcin");
  GLADE_HOOKUP_OBJECT (windowAG, labelAGFtelf, "labelAGFtelf");
  GLADE_HOOKUP_OBJECT (windowAG, labelAGFinva_nom, "labelAGFinva_nom");
  GLADE_HOOKUP_OBJECT (windowAG, labelAGFinva_prenom, "labelAGFinva_prenom");
  GLADE_HOOKUP_OBJECT (windowAG, labelAGFinva_chambre, "labelAGFinva_chambre");
  GLADE_HOOKUP_OBJECT (windowAG, buttonAGFajouter, "buttonAGFajouter");
  GLADE_HOOKUP_OBJECT (windowAG, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (windowAG, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (windowAG, image6, "image6");
  GLADE_HOOKUP_OBJECT (windowAG, label3, "label3");
  GLADE_HOOKUP_OBJECT (windowAG, labeltabAGF2, "labeltabAGF2");
  GLADE_HOOKUP_OBJECT (windowAG, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (windowAG, entryAGFmodifnom, "entryAGFmodifnom");
  GLADE_HOOKUP_OBJECT (windowAG, entryAGFmodifprenom, "entryAGFmodifprenom");
  GLADE_HOOKUP_OBJECT (windowAG, entryAGFmodifchambre, "entryAGFmodifchambre");
  GLADE_HOOKUP_OBJECT (windowAG, entryAGFmodiftelf, "entryAGFmodiftelf");
  GLADE_HOOKUP_OBJECT (windowAG, labelmodfnom, "labelmodfnom");
  GLADE_HOOKUP_OBJECT (windowAG, labelmodfniveau, "labelmodfniveau");
  GLADE_HOOKUP_OBJECT (windowAG, radiobuttonAGFm1, "radiobuttonAGFm1");
  GLADE_HOOKUP_OBJECT (windowAG, radiobuttonAGFm2, "radiobuttonAGFm2");
  GLADE_HOOKUP_OBJECT (windowAG, labelModfprenom, "labelModfprenom");
  GLADE_HOOKUP_OBJECT (windowAG, radiobuttonAGFm3, "radiobuttonAGFm3");
  GLADE_HOOKUP_OBJECT (windowAG, radiobuttonAGFm4, "radiobuttonAGFm4");
  GLADE_HOOKUP_OBJECT (windowAG, radiobuttonAGFm5, "radiobuttonAGFm5");
  GLADE_HOOKUP_OBJECT (windowAG, labelmodfchambre, "labelmodfchambre");
  GLADE_HOOKUP_OBJECT (windowAG, labelmodftelf, "labelmodftelf");
  GLADE_HOOKUP_OBJECT (windowAG, buttonAGFinfo, "buttonAGFinfo");
  GLADE_HOOKUP_OBJECT (windowAG, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (windowAG, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (windowAG, image4, "image4");
  GLADE_HOOKUP_OBJECT (windowAG, label1, "label1");
  GLADE_HOOKUP_OBJECT (windowAG, buttonAGFmodif, "buttonAGFmodif");
  GLADE_HOOKUP_OBJECT (windowAG, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (windowAG, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (windowAG, image5, "image5");
  GLADE_HOOKUP_OBJECT (windowAG, label2, "label2");
  GLADE_HOOKUP_OBJECT (windowAG, labeltabAGF3, "labeltabAGF3");
  GLADE_HOOKUP_OBJECT (windowAG, buttonAGFrechercher, "buttonAGFrechercher");
  GLADE_HOOKUP_OBJECT (windowAG, image2, "image2");
  GLADE_HOOKUP_OBJECT (windowAG, buttonAGFsupprimer, "buttonAGFsupprimer");
  GLADE_HOOKUP_OBJECT (windowAG, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (windowAG, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (windowAG, image7, "image7");
  GLADE_HOOKUP_OBJECT (windowAG, label4, "label4");
  GLADE_HOOKUP_OBJECT (windowAG, buttonwindocalculer, "buttonwindocalculer");
  GLADE_HOOKUP_OBJECT (windowAG, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (windowAG, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (windowAG, image8, "image8");
  GLADE_HOOKUP_OBJECT (windowAG, label5, "label5");
  GLADE_HOOKUP_OBJECT (windowAG, image12, "image12");
  GLADE_HOOKUP_OBJECT (windowAG, labelAGfespace, "labelAGfespace");
  GLADE_HOOKUP_OBJECT (windowAG, imagelogo, "imagelogo");
  GLADE_HOOKUP_OBJECT (windowAG, button_afficherAGF, "button_afficherAGF");
  GLADE_HOOKUP_OBJECT (windowAG, image3, "image3");
  GLADE_HOOKUP_OBJECT (windowAG, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (windowAG, labelAGFtime, "labelAGFtime");

  return windowAG;
}

GtkWidget*
create_WindowAGFsupprimer (void)
{
  GtkWidget *WindowAGFsupprimer;
  GtkWidget *fixed4;
  GtkWidget *buttonAGFsup_annuler;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image9;
  GtkWidget *label6;
  GtkWidget *buttonAGFsup_valider;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image10;
  GtkWidget *label7;
  GtkWidget *labelAGFsup;
  GtkWidget *labelAGFconf;

  WindowAGFsupprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (WindowAGFsupprimer), _("supprimer"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (WindowAGFsupprimer), fixed4);

  buttonAGFsup_annuler = gtk_button_new ();
  gtk_widget_show (buttonAGFsup_annuler);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonAGFsup_annuler, 72, 192);
  gtk_widget_set_size_request (buttonAGFsup_annuler, 104, 29);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonAGFsup_annuler), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image9 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox6), image9, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("ANNULER"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox6), label6, FALSE, FALSE, 0);

  buttonAGFsup_valider = gtk_button_new ();
  gtk_widget_show (buttonAGFsup_valider);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonAGFsup_valider, 200, 192);
  gtk_widget_set_size_request (buttonAGFsup_valider, 104, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttonAGFsup_valider), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox7), image10, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("VALIDER"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox7), label7, FALSE, FALSE, 0);

  labelAGFsup = gtk_label_new (_("\303\212tes-vous s\303\273r de vouloir supprimer ??"));
  gtk_widget_show (labelAGFsup);
  gtk_fixed_put (GTK_FIXED (fixed4), labelAGFsup, 24, 88);
  gtk_widget_set_size_request (labelAGFsup, 328, 25);

  labelAGFconf = gtk_label_new (_("CONFIRMATION"));
  gtk_widget_show (labelAGFconf);
  gtk_fixed_put (GTK_FIXED (fixed4), labelAGFconf, 0, 8);
  gtk_widget_set_size_request (labelAGFconf, 168, 24);

  g_signal_connect ((gpointer) buttonAGFsup_annuler, "clicked",
                    G_CALLBACK (on_buttonAGFsup_annuler_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAGFsup_valider, "clicked",
                    G_CALLBACK (on_buttonAGFsup_valider_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (WindowAGFsupprimer, WindowAGFsupprimer, "WindowAGFsupprimer");
  GLADE_HOOKUP_OBJECT (WindowAGFsupprimer, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (WindowAGFsupprimer, buttonAGFsup_annuler, "buttonAGFsup_annuler");
  GLADE_HOOKUP_OBJECT (WindowAGFsupprimer, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (WindowAGFsupprimer, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (WindowAGFsupprimer, image9, "image9");
  GLADE_HOOKUP_OBJECT (WindowAGFsupprimer, label6, "label6");
  GLADE_HOOKUP_OBJECT (WindowAGFsupprimer, buttonAGFsup_valider, "buttonAGFsup_valider");
  GLADE_HOOKUP_OBJECT (WindowAGFsupprimer, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (WindowAGFsupprimer, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (WindowAGFsupprimer, image10, "image10");
  GLADE_HOOKUP_OBJECT (WindowAGFsupprimer, label7, "label7");
  GLADE_HOOKUP_OBJECT (WindowAGFsupprimer, labelAGFsup, "labelAGFsup");
  GLADE_HOOKUP_OBJECT (WindowAGFsupprimer, labelAGFconf, "labelAGFconf");

  return WindowAGFsupprimer;
}

GtkWidget*
create_windowAGFcalculer (void)
{
  GtkWidget *windowAGFcalculer;
  GtkWidget *fixed5;
  GtkWidget *buttonAGF_back;
  GtkWidget *image1;
  GtkWidget *checkbuttonAGFcalcul_4;
  GtkWidget *checkbuttonAGFcalcul_5;
  GtkWidget *checkbuttonAGFcalcul_2;
  GtkWidget *checkbuttonAGFcalcul_3;
  GtkWidget *checkbuttonAGFcalcul_1;
  GtkWidget *labelAGFcalcul_somme;
  GtkWidget *button2AGFclaculer;
  GtkWidget *labelAGFcalculer;

  windowAGFcalculer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowAGFcalculer), _("Calculer"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (windowAGFcalculer), fixed5);

  buttonAGF_back = gtk_button_new ();
  gtk_widget_show (buttonAGF_back);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonAGF_back, 8, 16);
  gtk_widget_set_size_request (buttonAGF_back, 66, 29);

  image1 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_container_add (GTK_CONTAINER (buttonAGF_back), image1);

  checkbuttonAGFcalcul_4 = gtk_check_button_new_with_mnemonic (_("4\303\250me ann\303\251e"));
  gtk_widget_show (checkbuttonAGFcalcul_4);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbuttonAGFcalcul_4, 312, 288);
  gtk_widget_set_size_request (checkbuttonAGFcalcul_4, 118, 24);

  checkbuttonAGFcalcul_5 = gtk_check_button_new_with_mnemonic (_("5\303\250me ann\303\251e"));
  gtk_widget_show (checkbuttonAGFcalcul_5);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbuttonAGFcalcul_5, 320, 344);
  gtk_widget_set_size_request (checkbuttonAGFcalcul_5, 118, 24);

  checkbuttonAGFcalcul_2 = gtk_check_button_new_with_mnemonic (_("2\303\250me ann\303\251e"));
  gtk_widget_show (checkbuttonAGFcalcul_2);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbuttonAGFcalcul_2, 312, 176);
  gtk_widget_set_size_request (checkbuttonAGFcalcul_2, 118, 24);

  checkbuttonAGFcalcul_3 = gtk_check_button_new_with_mnemonic (_("3\303\250me ann\303\251e"));
  gtk_widget_show (checkbuttonAGFcalcul_3);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbuttonAGFcalcul_3, 312, 224);
  gtk_widget_set_size_request (checkbuttonAGFcalcul_3, 118, 24);

  checkbuttonAGFcalcul_1 = gtk_check_button_new_with_mnemonic (_("1\303\250re annee"));
  gtk_widget_show (checkbuttonAGFcalcul_1);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbuttonAGFcalcul_1, 304, 128);
  gtk_widget_set_size_request (checkbuttonAGFcalcul_1, 118, 24);

  labelAGFcalcul_somme = gtk_label_new ("");
  gtk_widget_show (labelAGFcalcul_somme);
  gtk_fixed_put (GTK_FIXED (fixed5), labelAGFcalcul_somme, 272, 432);
  gtk_widget_set_size_request (labelAGFcalcul_somme, 136, 32);

  button2AGFclaculer = gtk_button_new_with_mnemonic (_("Calculer"));
  gtk_widget_show (button2AGFclaculer);
  gtk_fixed_put (GTK_FIXED (fixed5), button2AGFclaculer, 192, 432);
  gtk_widget_set_size_request (button2AGFclaculer, 66, 29);

  labelAGFcalculer = gtk_label_new (_("<span foreground=\"red\"><b>Calculer la somme des etudiants  en :</b></span>"));
  gtk_widget_show (labelAGFcalculer);
  gtk_fixed_put (GTK_FIXED (fixed5), labelAGFcalculer, 8, 96);
  gtk_widget_set_size_request (labelAGFcalculer, 336, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelAGFcalculer), TRUE);

  g_signal_connect ((gpointer) buttonAGF_back, "clicked",
                    G_CALLBACK (on_buttonAGF_back_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonAGFcalcul_4, "toggled",
                    G_CALLBACK (on_checkbuttonAGFcalcul_4_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonAGFcalcul_5, "toggled",
                    G_CALLBACK (on_checkbuttonAGFcalcul_5_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonAGFcalcul_2, "toggled",
                    G_CALLBACK (on_checkbuttonAGFcalcul_2_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonAGFcalcul_3, "toggled",
                    G_CALLBACK (on_checkbuttonAGFcalcul_3_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonAGFcalcul_1, "toggled",
                    G_CALLBACK (on_checkbuttonAGFcalcul_1_toggled),
                    NULL);
  g_signal_connect ((gpointer) button2AGFclaculer, "clicked",
                    G_CALLBACK (on_button2AGFclaculer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowAGFcalculer, windowAGFcalculer, "windowAGFcalculer");
  GLADE_HOOKUP_OBJECT (windowAGFcalculer, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (windowAGFcalculer, buttonAGF_back, "buttonAGF_back");
  GLADE_HOOKUP_OBJECT (windowAGFcalculer, image1, "image1");
  GLADE_HOOKUP_OBJECT (windowAGFcalculer, checkbuttonAGFcalcul_4, "checkbuttonAGFcalcul_4");
  GLADE_HOOKUP_OBJECT (windowAGFcalculer, checkbuttonAGFcalcul_5, "checkbuttonAGFcalcul_5");
  GLADE_HOOKUP_OBJECT (windowAGFcalculer, checkbuttonAGFcalcul_2, "checkbuttonAGFcalcul_2");
  GLADE_HOOKUP_OBJECT (windowAGFcalculer, checkbuttonAGFcalcul_3, "checkbuttonAGFcalcul_3");
  GLADE_HOOKUP_OBJECT (windowAGFcalculer, checkbuttonAGFcalcul_1, "checkbuttonAGFcalcul_1");
  GLADE_HOOKUP_OBJECT (windowAGFcalculer, labelAGFcalcul_somme, "labelAGFcalcul_somme");
  GLADE_HOOKUP_OBJECT (windowAGFcalculer, button2AGFclaculer, "button2AGFclaculer");
  GLADE_HOOKUP_OBJECT (windowAGFcalculer, labelAGFcalculer, "labelAGFcalculer");

  return windowAGFcalculer;
}

