/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "timeee.h"
int
main (int argc, char *argv[])
{
  GtkWidget *windowAG,*labelAGFtim;
   GtkButton *button;
  char dtagf[300];

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ( "../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  windowAG = create_windowAG ();
  gtk_widget_show (windowAG);
 
  /*strcpy(dtagf,datetime());
  labelAGFtim = lookup_widget(button,"labelAGFtime") ;
  gtk_label_set_text(GTK_LABEL(labelAGFtim),dtagf);*/

  gtk_main ();
  return 0;
}

